# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jj-2rq7mOD0AZKFB2fzTgEVeqfjBMEFb
"""

def publisher():
	
	
	pub = rospy.Publisher('/std_id',
						String, queue_size=10)

	rospy.init_node('std_msgs/Int64', anonymous=True)
	
	
	rate = rospy.Rate(10)

	while not rospy.is_shutdown():
		data = "6352500722"
		

		rospy.loginfo(data)

		rate.sleep()